# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'tasker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tasker

  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'GoogleSignIn'
  pod 'FBSDKLoginKit'
  pod 'Firebase/Messaging'

  # Optionally, include the Swift extensions if you're using Swift.
  pod 'FirebaseFirestoreSwift'

end
